[Icon Theme]
Name=Classic
Comment=RespeQt bundled icon theme
Directories=oxygen-icons/16x16/actions,oxygen-icons/16x16/devices,oxygen-icons/16x16/filesystems,oxygen-icons/16x16@2/actions,oxygen-icons/16x16@2/devices,oxygen-icons/16x16@2/filesystems,oxygen-icons/16x16@3/actions,oxygen-icons/16x16@3/devices,oxygen-icons/16x16@3/filesystems,oxygen-icons/16x16@4/actions,oxygen-icons/16x16@4/devices,oxygen-icons/16x16@4/filesystems,Other/16x16,Other/16x16@2,Other/16x16@3,Other/16x16@4,silk-icons/16x16,silk-icons/16x16@2,silk-icons/16x16@3,silk-icons/16x16@4

[oxygen-icons/16x16/actions]
Size=16
Context=Actions
Type=Fixed

[oxygen-icons/16x16/devices]
Size=16
Context=Devices
Type=Fixed

[oxygen-icons/16x16/filesystems]
Size=16
Context=FileSystems
Type=Fixed

[oxygen-icons/16x16@2/actions]
Size=16
Scale=2
Context=Actions
Type=Fixed

[oxygen-icons/16x16@2/devices]
Size=16
Scale=2
Context=Devices
Type=Fixed

[oxygen-icons/16x16@2/filesystems]
Size=16
Scale=2
Context=FileSystems
Type=Fixed

[oxygen-icons/16x16@3/actions]
Size=16
Scale=3
Context=Actions
Type=Fixed

[oxygen-icons/16x16@3/devices]
Size=16
Scale=3
Context=Devices
Type=Fixed

[oxygen-icons/16x16@3/filesystems]
Size=16
Scale=3
Context=FileSystems
Type=Fixed

[oxygen-icons/16x16@4/actions]
Size=16
Scale=4
Context=Actions
Type=Fixed

[oxygen-icons/16x16@4/devices]
Size=16
Scale=4
Context=Devices
Type=Fixed

[oxygen-icons/16x16@4/filesystems]
Size=16
Scale=4
Context=FileSystems
Type=Fixed




[Other/16x16]
Size=16
Context=Other
Type=Fixed

[Other/16x16@2]
Size=16
Scale=2
Context=Other
Type=Fixed

[Other/16x16@3]
Size=16
Scale=3
Context=Other
Type=Fixed

[Other/16x16@4]
Size=16
Scale=4
Context=Other
Type=Fixed


[silk-icons/16x16]
Size=16
Context=Actions
Type=Fixed

[silk-icons/16x16@2]
Size=16
Scale=2
Context=Actions
Type=Fixed

[silk-icons/16x16@3]
Size=16
Scale=3
Context=Actions
Type=Fixed

[silk-icons/16x16@4]
Size=16
Scale=4
Context=Actions
Type=Fixed

