name: 32-bit MinGW builds
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  MinGW32_CI_build:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      contents: write # for actions/checkout to fetch code and softprops/action-gh-release
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: git make base-devel mingw-w64-i686-toolchain mingw-w64-i686-libtool mingw-w64-i686-nasm autoconf automake mingw-w64-i686-ncurses mingw-w64-i686-binutils mingw-w64-i686-libslirp
      - name: Ins<<tall Qt
          uses: jurplel/install-qt-action@v4
          with:
            version: '5.6.3'
            host: 'windows'
            target: 'desktop'
            arch: 'win32_mingw492'
            dir: '${{ github.workspace }}/Qt563/'
            install-deps: 'true'
            modules: 'qtpdf'
            archives: 'qtbase qtsvg qtcore qtwidgets qtgui qtnetwork qtprintsupport qtserialport qtlinguisttools'
            cache: 'false'
            cache-key-prefix: 'install-qt-action'
            setup-python: 'true'
            tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
            set-env: 'true'
            tools-only: 'false'
      - name: Build MinGW32 CMAKE
        run: |
          top=`pwd`
          mkdir -p $top/build
          cmake -B $top/build -S $top
          make -j4
          
